Models/Admin/ChangedModel.cs
using BlueGrassDigital.Models.Person;

namespace BlueGrassDigital.Models.Admin
{
    public class ChangedModel
    {
        public PersonResponse Original { get; set; }
        public PersonEdit Changed { get; set; }
        public List<string> ChangedProperties { get; set; }
    }
}

Models/Admin/PersonDetails.cs
using System.ComponentModel.DataAnnotations;

namespace BlueGrassDigital.Models.Admin
{
    public class PersonDetails
    {
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string AddressCountry { get; set; }
        [Required]
        public string AddressCity { get; set; }
        [Required]
        public string MobileNumber { get; set; }
        [Required]
        public string Email { get; set; }
        [Required]
        public string Gender { get; set; }

    }
}

Models/Admin/PersonEdit.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace BlueGrassDigital.Models.Admin
{
    public class PersonEdit
    {
        public string? FirstName { get; set; }

        public string LastName { get; set; }

        public string AddressCountry { get; set; }

        public string AddressCity { get; set; }

        public string MobileNumber { get; set; }

        public string Email { get; set; }

        public string Gender { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace BlueGrassDigital.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Person/MongoDbId.cs
using Newtonsoft.Json;

namespace BlueGrassDigital.Models.Person
{
    public class MongoDbId
    {
        [JsonProperty("oid")]
        public string Oid { get; set; }
    }
}

Models/Person/PersonResponse.cs
namespace BlueGrassDigital.Models.Person
{
    public class PersonResponse
    {
        public MongoDbId _id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AddressCountry { get; set; }
        public string AddressCity { get; set; }
        public string ProfilePicture { get; set; }
        public string MobileNumber { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
    }
}

Controllers/AdminController.cs
using BlueGrassDigital.Interface;
using BlueGrassDigital.Logic;
using BlueGrassDigital.Models.Admin;
using BlueGrassDigital.Models.Person;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BlueGrassDigital.Controllers
{ 
    public class AdminController : Controller
    {

        private readonly IAdmin _admin;
        private readonly IPerson _person;

        public AdminController(IAdmin Admin, IPerson Person)
        {
            _admin = Admin;
            _person = Person;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AddUser()
        {
            return View();
        }

        public IActionResult EditUser()
        {
            return View();
        }

        public async Task<IActionResult> PersonDetails(PersonDetails data)
        {
            return View(await _admin.AddPerson(data));
        }
        public async Task<IActionResult> Search(string Search)
        {
            return View("_AdminPersonView", await _person.GetAllPerson(Search));
        }

        public async Task<IActionResult> ViewChanged()
        {
            return View(await _admin.ViewChanged());
        }

    }
}

Controllers/HomeController.cs
using BlueGrassDigital.Interface;
using BlueGrassDigital.Models;
using BlueGrassDigital.Models.Person;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using static System.Net.Mime.MediaTypeNames;

namespace BlueGrassDigital.Controllers
{
    public class HomeController : Controller
    {

        private readonly IPerson _person;

        public HomeController(IPerson Person)
        {
            _person = Person;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> Search(string Search)
        {
            return View("_PersonView", await _person.GetAllPerson(Search));  
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Admin/AddUser.cshtml
@model BlueGrassDigital.Models.Admin.PersonDetails

<!-- Preloader -->
<div id="preloader" class="" style="display: none;">
    <div id="ctn-preloader" class="ctn-preloader">
        <div class="round_spinner">
            <div class="spinner"></div>
            <div class="text">
                <img src="img/logo/Logo-2.png" alt="">
            </div>
        </div>
        <h2 class="head">Did You Know?</h2>
        <p>We design Banca for the readers, optimizing not for page views or engagement</p>
    </div>
</div>
    <section class="breadcrumb-area">
        <div class="breadcrumb-widget  pt-200 pb-110" style="background-image: url(img/breadcrumb/bg-1.png);">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="breadcrumb-content pt-85">
                            <h1>Add User Details</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
  
    <section class="loan-deatils-area bg_disable pt-130 pb-120">
        <div class="container">
            <div class="row">

                <div class="col-lg-12">
                    <div class="loan-details-widget">
                    <form id="userDetailsForm" asp-controller="Admin" asp-action="PersonDetails" method="post">
                            <div class="row mb-35 gy-4">
                                <!-- New fields for capturing person details -->
                                <div class="col-md-6">
                                    <label class="label" for="personFirstName">First Name</label>
                                    <div class="input-field">
                                    <input type="text" class="form-control" id="personFirstName" name="FirstName" required>
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                    </div>
                                    
                                </div>
                                <div class="col-md-6">
                                    <label class="label" for="personLastName">Last Name</label>
                                <input type="text" class="form-control" id="personLastName" name="LastName" required>
                                <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>


                                <div class="col-md-6">
                                    <label class="label" for="personAddressCountry">Country</label>
                                <input type="text" class="form-control" id="personAddressCountry" name="AddressCountry" required autocomplete="off">
                                <span asp-validation-for="AddressCountry" class="text-danger"></span>
                                <div id="countrySuggestions"></div>
                                </div>
                                <div class="col-md-6">
                                    <label class="label" for="personAddressCity">City</label>
                                <input type="text" class="form-control" id="personAddressCity" name="AddressCity" required autocomplete="off">
                                <span asp-validation-for="AddressCity" class="text-danger"></span>
                                <div id="citySuggestions"></div>
                                </div>


                                <div class="col-md-6">
                                    <label class="label" for="personMobileNumber">Mobile Number</label>
                                <input type="number" class="form-control" id="personMobileNumber" name="MobileNumber" required>
                                <span asp-validation-for="MobileNumber" class="text-danger"></span>
                                </div>
                                <div class="col-md-6">
                                    <label class="label" for="personEmail">Email</label>
                                <input type="email" class="form-control" id="personEmail" name="Email" required>
                                <span asp-validation-for="Email" class="text-danger"></span>
                                </div>
                                <div class="col-md-6">
                                    <label class="label" for="personGender">Gender</label>
                                <select class="form-select" id="personGender" name="Gender" required>
                                        <option value="Male">Male</option>
                                        <option value="Female">Female</option>
                                        <option value="Other">Other</option>
                                    </select>
                                <span asp-validation-for="Gender" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row  mt-60">
                                <div class="col-md-12">
                                    <div class="nav-btn d-flex justify-content-end">
                                    <button class="theme-btn-primary_alt theme-btn next-btn" type="submit">Submit <i class="arrow_right"></i></button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>



<script>

    $(document).ready(function () {
       
        // // Function to fetch country suggestions
        // $('#personAddressCountry').keyup(function () {
         
        //     var query = $(this).val();
        //     if (query.length >= 3) {
        //         $.ajax({
        //             url: 'https://fidelityservicesgroup.simplify.hr/Lookup/ProvinceAutoCompleteLookup',
        //             type: 'POST',
        //             crossDomain: true,
        //             dataType: 'json',
        //             data: {
        //                 countryId: 1,
        //                 term: query
        //             },
        //             success: function (data) {
        //                 debugger;
        //                 var suggestions = data.geonames.map(function (place) {
        //                     return place.name;
        //                 });
        //                 $('#countrySuggestions').html(suggestions.join(', '));
                      
        //             }
        //         }).done(function (data) {

        //             debugger;

        //         });;
        //     } else {
        //         $('#countrySuggestions').html('');
        //     }
        // });

        // // Function to fetch city suggestions
        // $('#personAddressCity').keyup(function () {
        //     var query = $(this).val();
        //     if (query.length >= 3) {
        //         $.ajax({
        //             url: 'https://api.opencagedata.com/geocode/v1/json',
        //             type: 'GET',
        //             dataType: 'json',
        //             data: {
        //                 q: query,
        //                 country: 'ZA', // South Africa country code
        //                 maxRows: 5, // Maximum number of suggestions
        //                 username: 'demo' // Your Geonames username
        //             },
        //             success: function (data) {
        //                 var suggestions = data.geonames.map(function (place) {
        //                     return place.name;
        //                 });
        //                 $('#citySuggestions').html(suggestions.join(', '));
        //             }
        //         });
        //     } else {
        //         $('#citySuggestions').html('');
        //     }
        // });
   
    });
</script>

Views/Admin/EditUser.cshtml
@{
    ViewData["Title"] = "Edit Page";
}
<!-- Preloader -->
<div id="preloader" class="" style="display: none;">
    <div id="ctn-preloader" class="ctn-preloader">
        <div class="round_spinner">
            <div class="spinner"></div>
            <div class="text">
                <img src="img/logo/Logo-2.png" alt="">
            </div>
        </div>
        <h2 class="head">Did You Know?</h2>
        <p>Searching the database for the person youre looking for</p>
    </div>
</div>

<div class="slider-active slick-initialized slick-slider">
    <button type="button" class="slick-prev slick-arrow" style="display: block;"><i class="ti-angle-left"></i></button>
    <main>
        <section class="breadcrumb-area" id="banner_animation2" style="position: relative; transform: translate3d(0px, 0px, 0px); transform-style: preserve-3d; backface-visibility: hidden;">
    <div class="breadcrumb-widget breadcrumb-widget-2  pt-200 pb-145" style="background-image: url(img/banner/search.png);">

        <div class="shapes">
            <div class="one-shape shape-1" data-parallax="{&quot;x&quot;: 100, &quot;y&quot;: 0, &quot;rotateZ&quot;:0}" style="transform:translate3d(0.029px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); -webkit-transform:translate3d(0.029px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); ">
                <img src="img/breadcrumb/Polygon-1.png" alt="shape">
            </div>
            <div class="one-shape shape-2" data-parallax="{&quot;x&quot;: 200, &quot;y&quot;: 50, &quot;rotateZ&quot;:0}" style="transform:translate3d(0.029px, 0.029px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); -webkit-transform:translate3d(0.029px, 0.029px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); ">
                <img src="img/breadcrumb/Polygon-2.png" alt="shape">
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-lg-7 mx-auto">
                    <div class="breadcrumb-content pt-50">
                        <h1>Search our Directory</h1>
                        <div class="search-box mt-20">
                                    <form asp-controller="Admin" asp-action="Search">
                                        <div class="input-group">
                                            <input class="form-control" type="text" placeholder="Search..." id="Search" name="Search">
                                            <button class="search-btn input-group-append" type="submit">
                                                <svg class="svg-icon search-icon" style="width: 20px;" aria-labelledby="title desc" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 19.9 19.7"><title id="title">Search Icon</title><desc id="desc">A magnifying glass icon.</desc><g class="search-path" fill="none" stroke="#848F91"><path stroke-linecap="square" d="M18.5 18.3l-5.4-5.4" /><circle cx="8" cy="8" r="7" /></g></svg>
                                            </button>
                                        </div>
                                    </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

 <div id="SearchResult"></div>

    </main>
    </div>




<!-- jQuery code -->
<script>
    $(document).ready(function () {
       
        $("form").submit(function (event) {
           
            event.preventDefault();

    
            var searchText = $("#Search").val();
            $("#preloader").show();

            // Send an AJAX request to the controller
            $.ajax({
                url: "/Admin/Search", 
                method: "GET",
                data: { Search: searchText },
                success: function (data) {
                    $("#preloader").hide();
                    $("#SearchResult").html(data);
                },
                error: function (xhr, status, error) {
               
                    console.error(xhr.responseText);
                }
            });
        });
    });
</script>

Views/Admin/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h1>Login</h1>

<form asp-action="Login" method="post">
    <label for="username">Username:</label>
    <input type="text" id="username" name="username">
    <br>
    <label for="password">Password:</label>
    <input type="password" id="password" name="password">
    <br>
    <button type="submit">Login</button>
</form>

Views/Admin/PersonDetails.cshtml
<section class="breadcrumb-area" id="banner_animation2" style="position: relative; transform: translate3d(0px, 0px, 0px); transform-style: preserve-3d; backface-visibility: hidden;">
    <div style="background-color: #0050b2;" class="breadcrumb-widget breadcrumb-widget-2  pt-200 pb-145" style="background-image: url(img/banner/search.png);">

        <div class="shapes">
            <div class="one-shape shape-1" data-parallax="{&quot;x&quot;: 100, &quot;y&quot;: 0, &quot;rotateZ&quot;:0}" style="transform:translate3d(0.029px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); -webkit-transform:translate3d(0.029px, 0px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); ">
                <img src="img/breadcrumb/Polygon-1.png" alt="shape">
            </div>
            <div class="one-shape shape-2" data-parallax="{&quot;x&quot;: 200, &quot;y&quot;: 50, &quot;rotateZ&quot;:0}" style="transform:translate3d(0.029px, 0.029px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); -webkit-transform:translate3d(0.029px, 0.029px, 0px) rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1); ">
                <img src="img/breadcrumb/Polygon-2.png" alt="shape">
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-lg-7 mx-auto">
                    <div class="breadcrumb-content pt-50">
                        <h1> User has been Added</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Admin/ViewChanged.cshtml
@model List<BlueGrassDigital.Models.Admin.ChangedModel>
<section class="breadcrumb-area">
    <div style="background-color: #0050b2;" class="breadcrumb-widget  pt-110 pb-110" style="background-image: url(img/breadcrumb/bg-1.png);">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumb-content pt-85">
                        <h1>View Changed deatails</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="pt-200 pb-145 bg_disable">
    <div class="container pt-40">

        <div class="row gy-4 mt-30">
            @{
                var count = 1;
                foreach (var item in Model)
                {
                    if (item.Changed != null && item.ChangedProperties != null && item.Original != null)
                    {
                        <div class="col-md-6 col-lg-4"> 
                        <div class="feature-card-widget-7 wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                                <h4>Original #@count </h4>
                            <div class="row">
                                <div class="col col-12">
                                        <p> <Lable>FirstName: @item.Original.FirstName</Lable></p>
                                        <p> <Lable>LastName: @item.Original.LastName</Lable></p>
                                        <p> <Lable>Email: @item.Original.Email</Lable></p>
                                        <p> <Lable>MobileNumber: @item.Original.MobileNumber</Lable></p>
                                        <p> <Lable>Location: @item.Original.AddressCountry</Lable>  <label>@item.Original.AddressCity </label></p>
                                        <p> <Lable>Gender: @item.Original.Gender</Lable></p>
                                </div>
                            </div>
                        </div>
                        </div>
                        <div class="col-md-6 col-lg-4">
                            <div class="feature-card-widget-7 wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                                <h4>Changed #@count </h4>
                            <div class="row">
                                <div class="col col-12">
                                        <p> <Lable>FirstName: @item.Changed.FirstName</Lable></p>
                                        <p> <Lable>LastName: @item.Changed.LastName</Lable></p>
                                        <p> <Lable>Email: @item.Changed.Email</Lable></p>
                                        <p> <Lable>MobileNumber: @item.Changed.MobileNumber</Lable></p>
                                    <p> <Lable>Location: @item.Changed.AddressCountry</Lable>  <label>@item.Changed.AddressCity </label></p>
                                        <p> <Lable>Gender: @item.Changed.Gender</Lable></p>
                                </div>
                            </div>
                            </div>
                        </div>

                        <div class="col-md-6 col-lg-4">
                            <div class="feature-card-widget-7 wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                                <h4>What has Changed #@count </h4>
                                <div class="row">
                                    <div class="col col-12">
                                        @foreach (var x in item.ChangedProperties)
                                        {
                                            <p>
                                                @x has changed
                                            </p>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                       
                    }
                    count++;
                }
            }
    </div>
    </div>
</section>

Views/Home/_PersonView.cshtml
@model List<BlueGrassDigital.Models.Person.PersonResponse>

@if (Model != null && Model.Any())
{
    <section class="feature-jobs bg_white pt-125 pb-140">
        <div class="container">
            <div class="row justify-content-between align-items-center">
                <div class="col-md-6">
                    <div class="section-title text-start">
                        <h2 class="mb-0 wow fadeInRight" style="visibility: visible; animation-name: fadeInRight;">Customers</h2>
                    </div>
                </div>
            </div>

            <div class="row pt-60">
                <div class="col-lg-12">
                    <div class="feature-job-tab">
                        <ul class="feature-job-list">
                            @foreach (var person in Model)
                            {
                                <li style="cursor: pointer;">
                                    <a onclick="showPopup('@person.FirstName', '@person.LastName', '@person.AddressCity', '@person.AddressCountry', '@person.MobileNumber', '@person.Email', '@person.Gender');">
                                        <div class="single-feature-job wow fadeInUp" data-wow-delay="0.1s" style="visibility: visible; animation-delay: 0.1s; animation-name: fadeInUp;">
                                            <h6 class="job-title">@person.FirstName @person.LastName</h6>
                                            <div class="d-flex flex-wrap">
                                                <div class="job-location me-3">
                                                    <i class="icon_pin_alt"></i>@person.AddressCity, @person.AddressCountry
                                                </div>
                                                <div class="job-catagory">
                                                    <span>@person.MobileNumber</span> 
                                                </div>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <!-- Popup/Modal -->
        <div id="popup" class="popup">
            <div class="popup-content">
                <span class="close popup-close" onclick="closePopup()">&times;</span>
                <h2 style="color: black;" id="popupTitle" class="popup-title"></h2>
                <div id="popupDetails" class="popup-details"></div>
            </div>
        </div>

    </section>
}

<script>
    function showPopup(firstName, lastName, addressCity, addressCountry, mobileNumber, email, gender) {
        var popup = document.getElementById("popup");
        var popupTitle = document.getElementById("popupTitle");
        var popupDetails = document.getElementById("popupDetails");

        // Set popup title
        popupTitle.textContent = firstName + " " + lastName;

        // Set popup details with spaced out content
        popupDetails.innerHTML = "<strong>City:</strong> " + addressCity + "<br>" +
            "<strong>Country:</strong> " + addressCountry + "<br>" +
            "<strong>Mobile Number:</strong> " + mobileNumber + "<br>" +
            "<strong>Email:</strong> " + email + "<br>" +
            "<strong>Gender:</strong> " + gender;

        // Show the popup
        popup.style.display = "block";
    }
    function closePopup() {
        var popup = document.getElementById("popup");
        popup.style.display = "none";
    }
</script>

Views/Shared/_navbar.cshtml
<div class="header-menu header-menu-4" id="sticky" style="top: 0px;">
    <nav class="navbar navbar-expand-lg ">
        <div class="container">
            <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="menu_toggle">
                    <span class="hamburger">
                        <span></span>
                        <span></span>
                        <span></span>
                    </span>
                    <span class="hamburger-cross">
                        <span></span>
                        <span></span>
                    </span>
                </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav menu ms-auto">
                     <div class="nav-item">
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav menu ms-auto">

                            <li class="nav-item submenu">
                               <a class="nav-link" role="" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item dropdown submenu">
                                <p class="nav-link" role="button">Admin</p>
                                <i class="arrow_carrot-down_alt2 mobile_dropdown_icon" aria-hidden="false" data-bs-toggle="dropdown"></i>
                                <ul class="dropdown-menu ">
                                    <li class="nav-item"><a class="nav-link" role="button" asp-area="" asp-controller="Admin" asp-action="AddUser">Add User</a></li>
                                    <li class="nav-item"><a class="nav-link" role="button" asp-area="" asp-controller="Admin" asp-action="EditUser">Edit User</a></li>
                                        <li class="nav-item"><a class="nav-link" role="button" asp-area="" asp-controller="Admin" asp-action="ViewChanged">View Changed</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    </div>
                </div>
                <div class="px-2 js-darkmode-btn" title="Toggle dark mode">
                    <label for="something" class="tab-btn tab-btns">
                        <ion-icon name="moon" role="img" class="md hydrated" aria-label="moon"></ion-icon>
                    </label>
                    <label for="something" class="tab-btn">
                        <ion-icon name="sunny" role="img" class="md hydrated" aria-label="sunny"></ion-icon>
                    </label>
                    <label class=" ball" for="something" style="left: 3px;"></label>
                    <input type="checkbox" name="something" id="something" class="dark_mode_switcher">
                </div>
            </div>
        </div>
    </nav>
</div>